class BranchEntry {
    billDate: string;
    billNumber: string;
    branchCode: string;
    branchId: number;
    creditGLNo: string;
    currentStage: string;
    debitGLNo: string;
    errorResponse: string;
    fileId: string;
    id: number;
    ifscCode: string;
    instrumentBankName: string;
    instrumentBranchName: string;
    instrumentDate: string;
    instrumentNumber: string;
    instrumentType: string;
    journalMasterId: number;
    relatedAccountNo: string;
    remarks: string;
    reversalStatus: string;
    transactionAmount: number;
    transactionDate: string;
    transactionDescription: string;
    transactionId: string;
    transactionName: string;
    transactionResponse: string;
    transactionStatus: string;
    transactionType: string;
    udf1: string;
    udf2: string;
    udf3: string;
    udf4: string;
    udf5: string;
    udfDate1: string;
    udfDate2: string;
    udfDate3: string;
    valueDate: string;
    version: number;
}

export = BranchEntry;
